// components/layout.js

import { Box } from "@chakra-ui/react";
import Head from "next/head";
import { ReactElement, useState } from "react";
import { SidebarContent } from "./sidebar";
import styles from "./layout.module.scss";
import { useAppDispatch, useAppSelector } from "../hooks";
import { MainAction, MainReducer } from "../state/mainReducer";

interface LayoutProps {
    children: ReactElement;
}
export default function Layout({ children }: any) {
    // const [isOpen, setisOpen] = useState(true);
    const isOpen = useAppSelector(state => state.main.isOpenSidebar);
    const dispatch = useAppDispatch();
    return (
        <>
            <div className={styles.container}>
                {/* <Head>
                    <title>Qroi Monetization Admin</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head> */}

                <main className={styles.main}>
                    <SidebarContent
                        isOpen={isOpen}
                        onClose={() => dispatch(MainAction.toggleSidebar())}
                    ></SidebarContent>
                    <Box
                        transition="0.5s ease"
                        ml={{ base: 0, md: isOpen ? 60 : 24 }}
                        minHeight="100vh"
                        p={4}
                        display="flex"
                        flexDirection={"column"}
                    >
                        {children}
                        <Box flex={1}></Box>
                        <footer className={styles.footer}></footer>
                    </Box>
                </main>
            </div>
        </>
    );
}
